parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\ImportBggCsvCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\BggApiService:
        arguments:
            $bggToken: '%env(BGG_TOKEN)%'

    App\Service\JwtService:
        arguments:
            $jwtSecret: '%env(JWT_SECRET)%'
